name: 'Staging check'
#He
# Trigger this workflow whenever a pull request is opened against the repo's
# main branch or an existing pull request's head branch is updated.
on:
  push:
    branches:
      - staging

jobs:
  # Used by the "pipeline_update" job to deploy the bundle.
  # Bundle validation is automatically performed as part of this deployment.
  # If validation fails, this workflow fails.
  deploy:
    name: 'Deploy bundle'
    runs-on: ubuntu-latest
    env:
          DATABRICKS_HOST: https://dbc-067c5b48-781a.cloud.databricks.com/
          DATABRICKS_TOKEN: dapi90bdf4d7e0bf12880897da349963cc73
    steps:
      # Check out this repo, so that this workflow can access it.
      - uses: actions/checkout@v3

      # Download the Databricks CLI.
      # See https://github.com/databricks/setup-cli
      - uses: databricks/setup-cli@main
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      # Deploy the bundle to the "dev" target as defined
      # in the bundle's settings file.
      - run: python -m pip install --upgrade pip
      - run: pip install uv
      - run: pip install pytest
      - run: pip install databricks-connect==15.1.*
      
      - name: Run unit tests check
        run: |
          python -m pytest
      - run: databricks bundle validate --target dev
        working-directory: POC_AssetBundles